/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent

script put together by Mr.Zain
*/
package org.openrsc.server.npchandler.Heroes_Quest;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.npchandler.NpcHandler;



public class Gerrant implements NpcHandler {

	public void handleNpc(final Npc npc, final Player owner) throws Exception {
	
		npc.blockedBy(owner);
		owner.setBusy(true);
		
		Quest q = owner.getQuest(20);
		
		if(q != null) 
		{
			
		} 
	}
	

	
		
	
}