/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent
*/
//NPC ID: 256

package org.openrsc.server.npchandler.Heroes_Quest;
import org.openrsc.server.event.DelayedQuestChat;
import org.openrsc.server.event.SingleEvent;
import org.openrsc.server.model.ChatMessage;
import org.openrsc.server.model.InvItem;
import org.openrsc.server.model.MenuHandler;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.model.World;
import org.openrsc.server.npchandler.NpcHandler;



public class Trobert implements NpcHandler 
{

	public void handleNpc(final Npc npc, final Player owner) throws Exception 
	{
	
		npc.blockedBy(owner);
		owner.setBusy(true);
		
		Quest q = owner.getQuest(20);
		Quest blackarm = owner.getQuest(51);
		Quest phoenix = owner.getQuest(52);
		
		if (q == null)
		{
			noQuestStarted(npc, owner);
		}
		else
		{
			if(q != null) 
			{
				if(phoenix != null && phoenix.finished()) 
				{
					noQuestStarted(npc, owner);
				} 
				else 
				{
					switch(q.getStage())
					{
						case 3:
							onCandleJob(npc, owner);
						break;
						case 4:
							checkId(npc, owner);
						break;
						case 5:
							finishedCandleJob(npc, owner);
						break;
					}
				}
			} 
		}
	}
	
	//player shouldnt be inside
	private void noQuestStarted(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hi"}, true) 
		{
			public void finished() 
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"You shouldn't be in here"}) 
				{
					public void finished() 
					{
						owner.teleport(439, 687);
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}
	
	private void onCandleJob(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hi, welcome to our Brimhaven headquarters", "I'm Trobert and I'm in charge here"}, true) 
		{
			public void finished() 
			{
				World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
				{
					public void action()
					{
						final String[] options107 = {"So can you help me get Scarface Pete's candlesticks?", "Pleased to meet you"};
						owner.setBusy(false);
						owner.sendMenu(options107);
						owner.setMenuHandler(new MenuHandler(options107) 
						{
							public void handleReply(final int option, final String reply)
							{
								owner.setBusy(true);
								for(Player informee : owner.getViewArea().getPlayersInView())
								{
									informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
								}
								switch(option) 
								{
									case 0:
										World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Well we have made some progress there", "We know one of the keys to Pete's treasure room is carried by Grip the head guard", "So we thought it might be good to get close to the head guard", "Grip was taking on a new deputy called Hartigen", "Hartigen was an Asgarnian black knight", "However he was deserting the black knight fortress", "and seeking new employment", "We managed to waylay him on the way here", "We now have his i.d paper", "Next we need someone to impersonate the black knight"})
										{
											public void finished()
											{
												World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
												{
													public void action()
													{
														final String[] options107 = {"I volunteer to undertake that mission", "Well good luck then"};
														owner.setBusy(false);
														owner.sendMenu(options107);
														owner.setMenuHandler(new MenuHandler(options107) 
														{
															public void handleReply(final int option, final String reply)
															{
																owner.setBusy(true);
																for(Player informee : owner.getViewArea().getPlayersInView())
																{
																	informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																}
																switch(option) 
																{
																	case 0:
																		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Well here's the id", "Take that to the guard room at Scarface Pete's mansion"})
																		{
																			public void finished()
																			{
																				owner.incQuestCompletionStage(20);
																				owner.sendMessage("Trobert gives you Hartigen's ID paper");
																				owner.getInventory().add(573, 1);
																				owner.sendInventory();
																				owner.setBusy(false);
																				npc.unblock();
																			}
																		});
																	break;
																	case 1:
																		owner.setBusy(false);
																		npc.unblock();
																	break;
																}
															}
														});
													}
												});
											}
										});
									break;
									case 1:
										owner.setBusy(false);
										npc.unblock();
									break;
								}
							}
						});
					}
				});
			}
		});
	}
	
	private void checkId(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"get going mate", "you've got your ID paper already"}, true) 
		{
			public void finished() 
			{
				if (owner.getInventory().countId(573) >= 1 || owner.getBank().countId(573) >= 1)
				{
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Okay"}) 
					{
						public void finished() 
						{
							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Good luck"}) 
							{
								public void finished() 
								{
									owner.setBusy(false);
									npc.unblock();
								}
							});
						}
					});
				}
				else
				{
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"I seem to have lost my i.d paper", "You got another?"}) 
					{
						public void finished() 
						{
							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Sure here you go"}) 
							{
								public void finished() 
								{
									owner.sendMessage("Trobert gives you another ID paper");
									owner.setBusy(false);
									npc.unblock();
								}
							});
						}
					});
				}
			}
		});
	}
	
	private void finishedCandleJob(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"You get that candlestick?"}, true) 
		{
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"yeah I got it and gave it to Katrine"}) 
				{
					public void finished() 
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Good job mate"}) 
						{
							public void finished() 
							{
								owner.setBusy(false);
								npc.unblock();
							}
						});
					}
				});
			}
		});
	}
	
}