package com.openrsc.server.net.rsc.enums;

public enum OpcodeOut {
	SEND_LOGOUT_REQUEST_CONFIRM,
	SEND_QUESTS,
	SEND_DUEL_OPPONENTS_ITEMS,
	SEND_TRADE_ACCPETED,
	SEND_SERVER_CONFIGS, // inauthentic
	SEND_TRADE_OPEN_CONFIRM,
	SEND_WORLD_INFO,
	SEND_DUEL_SETTINGS,
	SEND_EXPERIENCE,
	SEND_EXPERIENCE_TOGGLE, // inauthentic
	SEND_BUBBLE, // used for teleport, telegrab, and iban's magic
	SEND_BANK_OPEN,
	SEND_SCENERY_HANDLER,
	SEND_PRIVACY_SETTINGS,
	SEND_SYSTEM_UPDATE,
	SEND_INVENTORY,
	SEND_ELIXIR, // inauthentic
	SEND_APPEARANCE_CHANGE,
	SEND_NPC_COORDS,
	SEND_DEATH,
	SEND_STOPSLEEP,
	SEND_PRIVATE_MESSAGE_SENT,
	SEND_BOX,
	SEND_INVENTORY_UPDATEITEM,
	SEND_BOUNDARY_HANDLER,
	SEND_TRADE_WINDOW,
	SEND_TRADE_OTHER_ITEMS,
	SEND_EXPSHARED, // inauthentic
	SEND_GROUND_ITEM_HANDLER,
	SEND_SHOP_OPEN,
	SEND_UPDATE_NPC,
	SEND_IGNORE_LIST,
	SEND_INPUT_BOX, // inauthentic
	SEND_ON_TUTORIAL,
	SEND_CLAN, // inauthentic
	SEND_IRONMAN, // inauthentic
	SEND_PARTY, // inauthentic
	SEND_FATIGUE,
	SEND_ON_BLACK_HOLE,
	SEND_SLEEPSCREEN,
	SEND_KILL_ANNOUNCEMENT, // inauthentic
	SEND_PRIVATE_MESSAGE,
	SEND_INVENTORY_REMOVE_ITEM,
	SEND_TRADE_CLOSE,
	SEND_COMBAT_STYLE, //inauthentic
	SEND_SERVER_MESSAGE,
	SEND_AUCTION_PROGRESS, // inauthentic
	SEND_FISHING_TRAWLER, // inauthentic
	SEND_PROGRESS_BAR, // inauthentic
	SEND_UPDATE_PROGRESS_BAR, // inauthentic
	SEND_REMOVE_PROGRESS_BAR, // inauthentic
	SEND_BANK_PIN_INTERFACE, // inauthentic
	SEND_ONLINE_LIST, // inauthentic
	SEND_SHOP_CLOSE,
	SEND_NPC_KILLS, // inauthentic
	SEND_FRIEND_UPDATE,
	SEND_BANK_PRESET, // inauthentic
	SEND_EQUIPMENT_STATS,
	SEND_STATS,
	SEND_STAT,
	SEND_UPDATE_STAT,
	SEND_TRADE_OTHER_ACCEPTED,
	SEND_LOGOUT,
	SEND_DUEL_CONFIRMWINDOW,
	SEND_DUEL_WINDOW,
	SEND_WELCOME_INFO,
	SEND_CANT_LOGOUT,
	SEND__BYTES_UNUSED,
	SEND_PLAYER_COORDS,
	SEND_SLEEPWORD_INCORRECT,
	SEND_BANK_CLOSE,
	SEND_PLAY_SOUND,
	SEND_PRAYERS_ACTIVE,
	SEND_DUEL_ACCEPTED,
	SEND_REMOVE_WORLD_ENTITY,
	SEND_APPEARANCE_KEEPALIVE,
	SEND_BOX2,
	SEND_OPEN_RECOVERY, // part of RSC protocol, would like available even on  setting
	SEND_DUEL_CLOSE,
	SEND_OPEN_DETAILS, // part of RSC protocol, would like available even on  setting
	SEND_UPDATE_PLAYERS,
	SEND_UPDATE_IGNORE_LIST_BECAUSE_NAME_CHANGE,
	SEND_GAME_SETTINGS,
	SEND_SLEEP_FATIGUE,
	SEND_OPTIONS_MENU_OPEN,
	SEND_BANK_UPDATE,
	SEND_OPTIONS_MENU_CLOSE,
	SEND_DUEL_OTHER_ACCEPTED,
	SEND_EQUIPMENT, // inauthentic
	SEND_EQUIPMENT_UPDATE; // inauthentic
}
