package com.openrsc.server.net.rsc.enums;

public enum OpcodeIn {
	HEARTBEAT,
	WALK_TO_ENTITY,
	WALK_TO_POINT,
	CONFIRM_LOGOUT,
	LOGOUT,
	BLINK,
	COMBAT_STYLE_CHANGED,
	QUESTION_DIALOG_ANSWER,

	PLAYER_APPEARANCE_CHANGE,
	SOCIAL_ADD_IGNORE,
	SOCIAL_ADD_DELAYED_IGNORE, // custom
	SOCIAL_ADD_FRIEND,
	SOCIAL_SEND_PRIVATE_MESSAGE,
	SOCIAL_REMOVE_FRIEND,
	SOCIAL_REMOVE_IGNORE,

	DUEL_FIRST_SETTINGS_CHANGED,
	DUEL_FIRST_ACCEPTED,
	DUEL_DECLINED,
	DUEL_OFFER_ITEM,
	DUEL_SECOND_ACCEPTED,

	INTERACT_WITH_BOUNDARY,
	INTERACT_WITH_BOUNDARY2,
	CAST_ON_BOUNDARY,
	USE_WITH_BOUNDARY,

	NPC_TALK_TO,
	NPC_COMMAND,
	NPC_COMMAND2, // custom
	NPC_ATTACK,
	CAST_ON_NPC,
	NPC_USE_ITEM,

	PLAYER_CAST_PVP,
	PLAYER_USE_ITEM,
	PLAYER_ATTACK,
	PLAYER_DUEL,
	PLAYER_INIT_TRADE_REQUEST,
	PLAYER_FOLLOW,

	CAST_ON_GROUND_ITEM,
	GROUND_ITEM_USE_ITEM,
	GROUND_ITEM_TAKE,

	CAST_ON_INVENTORY_ITEM,
	ITEM_USE_ITEM,
	ITEM_UNEQUIP_FROM_INVENTORY,
	ITEM_EQUIP_FROM_INVENTORY,
	ITEM_UNEQUIP_FROM_EQUIPMENT, // custom
	ITEM_EQUIP_FROM_BANK, // custom
	ITEM_REMOVE_TO_BANK, // custom
	ITEM_COMMAND,
	ITEM_DROP,

	CAST_ON_SELF,
	CAST_ON_LAND,

	OBJECT_COMMAND,
	OBJECT_COMMAND2,
	CAST_ON_SCENERY,
	USE_ITEM_ON_SCENERY,

	SHOP_CLOSE,
	SHOP_BUY,
	SHOP_SELL,

	PLAYER_ACCEPTED_INIT_TRADE_REQUEST,
	PLAYER_DECLINED_TRADE,
	PLAYER_ADDED_ITEMS_TO_TRADE_OFFER,
	PLAYER_ACCEPTED_TRADE,

	PRAYER_ACTIVATED,
	PRAYER_DEACTIVATED,

	GAME_SETTINGS_CHANGED,
	CHAT_MESSAGE,
	COMMAND,
	PRIVACY_SETTINGS_CHANGED,
	REPORT_ABUSE,
	BANK_CLOSE,
	BANK_WITHDRAW,
	BANK_DEPOSIT,

	BANK_DEPOSIT_ALL_FROM_INVENTORY, // custom
	BANK_DEPOSIT_ALL_FROM_EQUIPMENT, // custom
	BANK_SAVE_PRESET, // custom
	BANK_LOAD_PRESET, // custom
	INTERFACE_OPTIONS, // custom

	SLEEPWORD_ENTERED,

	SKIP_TUTORIAL,
	ON_BLACK_HOLE, // custom
	NPC_DEFINITION_REQUEST, // custom

	LOGIN,
	RELOGIN, // retro rsc
	REGISTER_ACCOUNT, // part of rsc era protocol
	FORGOT_PASSWORD, // part of rsc era protocol
	RECOVERY_ATTEMPT, // part of rsc era protocol

	CHANGE_RECOVERY_REQUEST, // part of rsc era protocol
	CHANGE_DETAILS_REQUEST, // part of rsc era protocol

	CHANGE_PASS, // part of rsc era protocol
	SET_RECOVERY, // part of rsc era protocol
	SET_DETAILS, // part of rsc era protocol

	CANCEL_RECOVERY_REQUEST, // part of rsc era protocol

	SEND_DEBUG_INFO, // part of rsc era protocol
	KNOWN_PLAYERS, // part of rsc era protocol
}
