package com.openrsc.server.net.rsc.enums;

public enum OpcodeOut {
	SEND_LOGOUT_REQUEST_CONFIRM,
	SEND_QUESTS,
	SEND_DUEL_OPPONENTS_ITEMS,
	SEND_TRADE_ACCEPTED,
	SEND_SERVER_CONFIGS, // custom
	SEND_TRADE_OPEN_CONFIRM,
	SEND_WORLD_INFO,
	SEND_DUEL_SETTINGS,
	SEND_EXPERIENCE,
	SEND_EXPERIENCE_TOGGLE, // custom
	SEND_BUBBLE, // used for teleport, telegrab, and iban's magic
	SEND_BANK_OPEN,
	SEND_SCENERY_HANDLER,
	SEND_PRIVACY_SETTINGS,
	SEND_SYSTEM_UPDATE,
	SEND_INVENTORY,
	SEND_ELIXIR, // custom
	SEND_APPEARANCE_SCREEN,
	SEND_NPC_COORDS,
	SEND_DEATH,
	SEND_STOPSLEEP,
	SEND_PRIVATE_MESSAGE_SENT,
	SEND_BOX,
	SEND_INVENTORY_UPDATEITEM,
	SEND_BOUNDARY_HANDLER,
	SEND_TRADE_WINDOW,
	SEND_TRADE_OTHER_ITEMS,
	SEND_EXPSHARED, // custom
	SEND_GROUND_ITEM_HANDLER,
	SEND_SHOP_OPEN,
	SEND_UPDATE_NPC,
	SEND_FRIEND_LIST, // retro rsc
	SEND_IGNORE_LIST,
	SEND_INPUT_BOX, // custom
	SEND_ON_TUTORIAL,
	SEND_CLAN, // custom
	SEND_CLAN_LIST, // custom
	SEND_CLAN_SETTINGS, // custom
	SEND_IRONMAN, // custom
	SEND_PARTY, // custom
	SEND_PARTY_LIST, // custom
	SEND_PARTY_SETTINGS, // custom
	SEND_FATIGUE,
	SEND_ON_BLACK_HOLE, // custom
	SEND_SLEEPSCREEN,
	SEND_KILL_ANNOUNCEMENT, // custom
	SEND_PRIVATE_MESSAGE,
	SEND_INVENTORY_REMOVE_ITEM,
	SEND_TRADE_CLOSE,
	SEND_COMBAT_STYLE,  // custom
	SEND_SERVER_MESSAGE,
	SEND_AUCTION_PROGRESS, // custom
	SEND_FISHING_TRAWLER, // custom
	SEND_STATUS_PROGRESS_BAR, // custom
	SEND_BANK_PIN_INTERFACE, // custom
	SEND_ONLINE_LIST, // custom
	SEND_SHOP_CLOSE,
	SEND_OPENPK_POINTS_TO_GP_RATIO, // custom
	SEND_NPC_KILLS, // custom
	SEND_OPENPK_POINTS, // custom
	SEND_FRIEND_UPDATE,
	SEND_BANK_PRESET, // custom
	SEND_EQUIPMENT_STATS,
	SEND_STATS,
	SEND_STAT,
	SEND_UPDATE_STAT,
	SEND_TRADE_OTHER_ACCEPTED,
	SEND_LOGOUT,
	SEND_DUEL_CONFIRMWINDOW,
	SEND_DUEL_WINDOW,
	SEND_WELCOME_INFO,
	SEND_CANT_LOGOUT,
	SEND_28_BYTES_UNUSED,
	SEND_PLAYER_COORDS,
	SEND_SLEEPWORD_INCORRECT,
	SEND_BANK_CLOSE,
	SEND_PLAY_SOUND,
	SEND_PRAYERS_ACTIVE,
	SEND_DUEL_ACCEPTED,
	SEND_REMOVE_WORLD_ENTITY,
	SEND_APPEARANCE_KEEPALIVE,
	SEND_BOX2,
	SEND_OPEN_RECOVERY, // part of rsc era protocol
	SEND_DUEL_CLOSE,
	SEND_OPEN_DETAILS, // part of rsc era protocol
	SEND_UPDATE_PLAYERS,
	SEND_UPDATE_PLAYERS_RETRO, // retro rsc protocol what later became SEND_UPDATE_PLAYERS type 5
	SEND_UPDATE_IGNORE_LIST_BECAUSE_NAME_CHANGE,
	SEND_GAME_SETTINGS,
	SEND_SLEEP_FATIGUE,
	SEND_OPTIONS_MENU_OPEN,
	SEND_BANK_UPDATE,
	SEND_OPTIONS_MENU_CLOSE,
	SEND_DUEL_OTHER_ACCEPTED,
	SEND_EQUIPMENT, // custom
	SEND_EQUIPMENT_UPDATE, // custom
	SEND_REMOVE_WORLD_NPC, // retro rsc protocol
	SEND_REMOVE_WORLD_PLAYER, // retro rsc protocol
	RUNESCAPE_UPDATED, // rsc era protocol
	SEND_YOPTIN, // added by mudclient 61 (or earlier, but post 40) and missing by 93 (present in mudclient 75)
	SEND_INVENTORY_SIZE, // known to be in mudclient69 to 75
    SEND_UNLOCKED_APPEARANCES, // custom
}
