/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent
*/

//scripted by Mr. Zain

package org.openrsc.server.npchandler.Tree_Gnome_Village;
import org.openrsc.server.Config;
import org.openrsc.server.event.DelayedQuestChat;
import org.openrsc.server.event.SingleEvent;
import org.openrsc.server.model.ChatMessage;
import org.openrsc.server.model.MenuHandler;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.model.Quests;
import org.openrsc.server.model.World;
import org.openrsc.server.npchandler.NpcHandler;



public class Montai implements NpcHandler {

	public void handleNpc(final Npc npc, final Player owner) throws Exception {
		npc.blockedBy(owner);
		owner.setBusy(true);
		Quest q = owner.getQuest(Quests.TREE_GNOME_VILLAGE);
		if(q != null) {
			if(q.finished()) {
				finished(npc, owner);
			} else {
				switch(q.getStage()) {
					case 0:
						noQuestStarted(npc, owner);
						break;
					case 1:
						questStage1(npc, owner);
						break;
					case 2:
						questStage2(npc, owner);
						break;
					case 3:
						questStage3(npc, owner);
						break;
					case 4:
						questStage4(npc, owner);
						break;
					case 5:
						questStage5(npc, owner);
						break;
					case 6:
						finished(npc, owner);
						break;
				}
			}
		} else {
			noQuestStarted(npc, owner);
		}
	}
	
	private void noQuestStarted(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"This is no place for a civilian", "get out of here!"}) {
			public void finished() {
			owner.setBusy(false);
			npc.unblock();
			}
		});
	}

	private void questStage1(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello"}, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello traveller", "are you here to help or just to watch?"}) {
					public void finished() {
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"I've been sent by king Bolren", "to retrieve the orb of protection"}) {
							public void finished() {
								World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Excellent we need all the help we can get", "I'm commander Montai", "the orb is in khazard stronghold to the north", "but until we weaken their defences", "we can't get close"}) {
									public void finished() {
										World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"What can I do?"}) {
											public void finished() {
												World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"First we need to strengthen our own defences", "We desperately need wood to make more battlements", "six loads of logs should do it", "once the battlements are gone it's all over"}) {
													public void finished() {
														World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
															public void action() {
																final String[] options107 = {"Ok, I'll gather some wood", "Sorry I no longer want to be involved"};
																owner.setBusy(false);
																owner.sendMenu(options107);
																owner.setMenuHandler(new MenuHandler(options107) {
																	public void handleReply(final int option, final String reply) {
																		owner.setBusy(true);
																		for(Player informee : owner.getViewArea().getPlayersInView()) {
																			informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																		}
																		switch(option) {
																			case 0:
																				questStage2Accepted(npc, owner);
																				break;
																			case 1:
																				owner.setBusy(false);
																				npc.unblock();
																				break;
																		}
																	}
																});
															}
														});
													}
												});
											}
										});
									}
								});
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage2Accepted(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Please be as quick as you can", "I don't know how much longer we can hold out"}) {
			public void finished() {
			owner.incQuestCompletionStage(Quests.TREE_GNOME_VILLAGE);
			owner.setBusy(false);
			npc.unblock();
			}
		});
	}
	
	private void questStage2(final Npc npc, final Player owner) {
		if(owner.getInventory().countId(14) < 6) {
			World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello"}, true) {
				public void finished() {
					World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello again, we're still desperate for wood soldier"}) {
						public void finished() {
							World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Looks like I don't have enough, I'll keep chopping"}) {
								public void finished() {
									World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Please be as quick as you can", "6 logs should be enough",  "I don't know how much longer we can hold out"}) {
										public void finished() {
											owner.setBusy(false);
											npc.unblock();
										}
									});
								}
							});
						}
					});
				}
			});
		}
		else
		if(owner.getInventory().countId(14) > 5) {
			World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello"}, true) {
				public void finished() {
					World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello again, we're still desperate for wood soldier"}) {
						public void finished() {
							World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"I have some here"}) {
								public void finished() {
									owner.sendMessage("You give some wood to the commander");
									owner.getInventory().remove(14, 1);
									owner.getInventory().remove(14, 1);
									owner.getInventory().remove(14, 1);
									owner.getInventory().remove(14, 1);
									owner.getInventory().remove(14, 1);
									owner.getInventory().remove(14, 1);
									owner.sendInventory();
									owner.incQuestCompletionStage(Quests.TREE_GNOME_VILLAGE);
									World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"That's excellent now we can make more defensive battlements", "give me a moment to organise the troops", "and then come speak to me", "I'll inform you of our next phase of attack"}) {
										public void finished() {
											owner.setBusy(false);
											npc.unblock();
										}
									});
								}
							});
						}
					});
				}
			});
		}
	}
	
	private void questStage3(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"How are you doing Montai?"}, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"We're hanging in there soldier", "for the next phase of the attack", "we need to breech their stronghold", "the ballista can break through the stronghold wall", "and then we can advance and seize back the orb"}) {
					public void finished() {
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"So what's the problem?"}) {
							public void finished() {
								World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"From this distance we can't get an accurate shot away", "We need the correct coordinates of the stronghold", "I've sent out three tracker gnomes to gather them"}) {
									public void finished() {
										World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Have they returned?"}) {
											public void finished() {
												World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"I'm afraid not and we're running out of time", "I need you to go into the heart of the battlefield", "find the trackers and bring back the coordinates", "Do you think you can do it?"}) {
													public void finished() {
														World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
															public void action() {
																final String[] options107 = {"No, I've had enough of your battle", "I'll try my best"};
																owner.setBusy(false);
																owner.sendMenu(options107);
																owner.setMenuHandler(new MenuHandler(options107) {
																	public void handleReply(final int option, final String reply) {
																		owner.setBusy(true);
																		for(Player informee : owner.getViewArea().getPlayersInView()) {
																			informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																		}
																		switch(option) {
																			case 0:
																				owner.setBusy(false);
																				npc.unblock();		
																			break;
																			
																			case 1:
																				questStage4Accepted(npc, owner);
																			break;
																		}
																	}
																});
															}
														});
													}
												});
											}
										});
									}
								});
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage4Accepted(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Thank you, You're braver than most", "I don't know how long I will be able to hold out", "Once you have the coordinates", "Come back and fire the ballista", "Right into those monsters", "If you can retrieve the orb and bring safety back to my people", "None of the blood spilled on this field will be in vain"}) {
			public void finished() {
			owner.incQuestCompletionStage(Quests.TREE_GNOME_VILLAGE);
			owner.setBusy(false);
			npc.unblock();
			}
		});
	}
	
	private void questStage4(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello"}, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello warrior, we need the coordinates", "For a direct hit from the ballista", "Once you have a direct hit you will be able", "To enter the stronghold and retrieve the orb"}) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}	
				});		
			}
		});
	}
		
	private void questStage5(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"I have blasted a hole in the stronghold"}, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Well done warrior", "Go collect the orb of protection from within"}) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}	
				});		
			}
		});
	}
	
	
	private void finished(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello again soldier", "thank you for your help"}) {
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"No problem"}) {
					public void finished() {
					owner.setBusy(false);
					npc.unblock();
					}
				});
			}
		});
	}
	
}