version: '3.1'
services:

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./etc/nginx:/etc/nginx/conf.d"
            - "./Website:/var/www/html"
            - "./etc/nginx/logs:/var/log/nginx"
            - "./etc/letsencrypt:/etc/letsencrypt"
            - "./server/avatars:/var/www/html/avatars"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always

    php:
        build:
            context: .
            dockerfile: etc/php/Dockerfile
        container_name: php
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./Website:/var/www/html"
        environment:
            - XDEBUG=false

    mysqldb:
        image: mariadb:latest
        container_name: mysql
        restart: always
        env_file:
            - ".env"
        command: [
            '--wait_timeout=360000',
            '--log-bin=bin.log',
            '--log-bin-index=bin-log.index',
            '--max_binlog_size=100M',
            '--binlog-format=MIXED',
            '--slow-query-log',
            '--general_log=1',
            '--expire_logs_days=10',
            '--sync_binlog=1'
            ]
        environment:
            - MYSQL_DATABASE=mysql
            - MYSQL_ROOT_USER=${MARIADB_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASS}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./etc/mariadb/innodb.cnf:/etc/mysql/conf.d/innodb.cnf:ro"
            - "./etc/logs/mariadb:/var/log/mysql"
