package com.openrsc.server.plugins.shared.constants;

public class Quests {

	public static final String NONE = "NONE", BLACK_KNIGHTS_FORTRESS = "BLACK_KNIGHTS_FORTRESS",
		COOKS_ASSISTANT = "COOKS_ASSISTANT", DEMON_SLAYER = "DEMON_SLAYER",
		DORICS_QUEST = "DORICS_QUEST", THE_RESTLESS_GHOST = "THE_RESTLESS_GHOST",
		GOBLIN_DIPLOMACY = "GOBLIN_DIPLOMACY", ERNEST_THE_CHICKEN = "ERNEST_THE_CHICKEN",
		IMP_CATCHER = "IMP_CATCHER", PIRATES_TREASURE = "PIRATES_TREASURE",
		PRINCE_ALI_RESCUE = "PRINCE_ALI_RESCUE", ROMEO_N_JULIET = "ROMEO_N_JULIET",
		SHEEP_SHEARER = "SHEEP_SHEARER", SHIELD_OF_ARRAV = "SHIELD_OF_ARRAV",
		THE_KNIGHTS_SWORD = "THE_KNIGHTS_SWORD", VAMPIRE_SLAYER = "VAMPIRE_SLAYER",
		WITCHS_POTION = "WITCHS_POTION", DRAGON_SLAYER = "DRAGON_SLAYER",
		WITCHS_HOUSE = "WITCHS_HOUSE", LOST_CITY = "LOST_CITY",
		HEROS_QUEST = "HEROS_QUEST", DRUIDIC_RITUAL = "DRUIDIC_RITUAL",
		MERLINS_CRYSTAL = "MERLINS_CRYSTAL", SCORPION_CATCHER = "SCORPION_CATCHER",
		FAMILY_CREST = "FAMILY_CREST", TRIBAL_TOTEM = "TRIBAL_TOTEM",
		FISHING_CONTEST = "FISHING_CONTEST", MONKS_FRIEND = "MONKS_FRIEND",
		TEMPLE_OF_IKOV = "TEMPLE_OF_IKOV", CLOCK_TOWER = "CLOCK_TOWER",
		THE_HOLY_GRAIL = "THE_HOLY_GRAIL", FIGHT_ARENA = "FIGHT_ARENA",
		TREE_GNOME_VILLAGE = "TREE_GNOME_VILLAGE", THE_HAZEEL_CULT = "THE_HAZEEL_CULT",
		SHEEP_HERDER = "SHEEP_HERDER", PLAGUE_CITY = "PLAGUE_CITY",
		SEA_SLUG = "SEA_SLUG", WATERFALL_QUEST = "WATERFALL_QUEST",
		BIOHAZARD = "BIOHAZARD", JUNGLE_POTION = "JUNGLE_POTION",
		GRAND_TREE = "GRAND_TREE", SHILO_VILLAGE = "SHILO_VILLAGE",
		UNDERGROUND_PASS = "UNDERGROUND_PASS", OBSERVATORY_QUEST = "OBSERVATORY_QUEST",
		TOURIST_TRAP = "TOURIST_TRAP", WATCHTOWER = "WATCHTOWER",
		DWARF_CANNON = "DWARF_CANNON", MURDER_MYSTERY = "MURDER_MYSTERY",
		DIGSITE = "DIGSITE", GERTRUDES_CAT = "GERTRUDES_CAT",
		LEGENDS_QUEST = "LEGENDS_QUEST", RUNE_MYSTERIES = "RUNE_MYSTERIES",
		PEELING_THE_ONION = "PEELING_THE_ONION";
}
