<?php

/**
 * New reCAPTCHA plugin for FluxBB
 *
 * Created by Franz Liedke
 * DAVVE 2015 ^ FIXED FOR LUNA SOFTWARE.
 */

// Make sure no one attempts to run this script "directly"
if (!defined('FORUM'))
    exit;

// Tell loader.php that this is indeed a plugin and that it is loaded
define('LUNA_PLUGIN_LOADED', 1);

// Store the config
if (isset($_POST['process_form']))
{
    $site_key = isset($_POST['recaptcha_site_key']) ? luna_trim($_POST['recaptcha_site_key']) : '';
    $secret_key = isset($_POST['recaptcha_secret_key']) ? luna_trim($_POST['recaptcha_secret_key']) : '';

    foreach (compact('site_key', 'secret_key') as $key => $value)
    {
        $key = 'recaptcha_'.$key;

        if (isset($luna_config[$key]))
            $db->query('UPDATE '.$db->prefix.'config SET conf_value = \''.$db->escape($value).'\' WHERE conf_name = \''.$db->escape($key).'\'') or error('Unable to update config value for '.$key, __FILE__, __LINE__, $db->error());
        else
            $db->query('INSERT INTO '.$db->prefix.'config (conf_name, conf_value) VALUES (\''.$db->escape($key).'\', \''.$db->escape($value).'\')') or error('Unable to store config value for '.$key, __FILE__, __LINE__, $db->error());
    }

   // Regenerate the config cache
	if (!defined('LUNA_CACHE_FUNCTIONS_LOADED'))
		require LUNA_ROOT.'include/cache.php';

	generate_config_cache();
	clear_feed_cache();

    redirect('backstage/loader.php?plugin=AP_reCAPTCHA.php', 'Settings saved successfully. Redirecting...');
}


define('LUNA_ACTIVE_PAGE', 'admin');
?>
    <form class="form-horizontal" id="recaptcha" method="post" action="<?php echo $_SERVER['REQUEST_URI'] ?>">
	<div class="panel panel-default">
        <div class="panel-heading">
			<h3 class="panel-title">Configure reCAPTCHA integration</h3>
		</div>
		<div class="panel-body">
            <fieldset>
                <p>
                Please provide your reCAPTCHA account credentials as provided by Google.
                </p>
				<div class="form-group">
					<label class="col-sm-3 control-label">Site key<span class="help-block">The key generated by google for site verification</span></label>
					<div class="col-sm-9">
						<input type="text" class="form-control" name="recaptcha_site_key" size="40" value="<?php if (!empty($luna_config['recaptcha_site_key'])) echo luna_htmlspecialchars($luna_config['recaptcha_site_key']); ?>" tabindex="1" />
                                
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-3 control-label">Secret key<span class="help-block">The secret key generated by google for server-side verification</span></label>
					<div class="col-sm-9">
                        <input type="text" class="form-control" name="recaptcha_secret_key" size="40" value="<?php if (!empty($luna_config['recaptcha_secret_key'])) echo luna_htmlspecialchars($luna_config['recaptcha_secret_key']); ?>" tabindex="2" />   
					</div>
				</div>
            </fieldset>
            <input class="btn btn-primary" type="submit" name="process_form" value="Save" />
		</div>
	</div>
    </form>