/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent
*/
package org.openrsc.server.npchandler.Dorics_Quest;

import org.openrsc.server.Config;
import org.openrsc.server.event.SingleEvent;
import org.openrsc.server.logging.Logger;
import org.openrsc.server.logging.model.eventLog;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.ChatMessage;
import org.openrsc.server.model.MenuHandler;
import org.openrsc.server.model.World;
import org.openrsc.server.event.DelayedQuestChat;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.model.InvItem;
import org.openrsc.server.npchandler.NpcHandler;
import org.openrsc.server.util.DataConversions;
public class Doric implements NpcHandler {

	public void handleNpc(final Npc npc, final Player owner) throws Exception {
		npc.blockedBy(owner);
		owner.setBusy(true);
		Quest q = owner.getQuest(Config.Quests.DORICS_QUEST);
		if(q != null) {
			if(q.finished()) {
				questFinished(npc, owner);
			} else {
				questStarted(npc, owner);
			}
		} else {
			questNotStarted(npc, owner);
		}
	}
	
	private void questNotStarted(final Npc npc, final Player owner) {
		final String[] messages18 = {"Hello traveller, what brings you to my humble smithy?"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages18, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
					public void action() {
						final String[] options2 = {"I wanted to use your anvils", "Mind your own business, shortstuff", "I was just checking out the landscape", "What do you make here?"};
						owner.setBusy(false);
						owner.sendMenu(options2);
						owner.setMenuHandler(new MenuHandler(options2) {
							public void handleReply(final int option, final String reply) {
								owner.setBusy(true);
								for(Player informee : owner.getViewArea().getPlayersInView()) {
									informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
								}
								switch(option) {
									case 0:
										final String[] messages19 = {"My anvils get enough work with my own use", "I make amulets, it takes a lot of work.", "If you could get me some more materials I could let you use them"};
										World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages19) {
											public void finished() {
												World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
													public void action() {
														final String[] options3 = {"Yes I will get you materials", "No, hitting rocks is for the boring people, sorry."};
														owner.setBusy(false);
														owner.sendMenu(options3);
														owner.setMenuHandler(new MenuHandler(options3) {
															public void handleReply(final int option, final String reply) {
																owner.setBusy(true);
																for(Player informee : owner.getViewArea().getPlayersInView()) {
																	informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																}
																switch(option) {
																	case 0:
																		final String[] messages20 = {"Well, clay is what I use more than anything, I make casts", "Could you get me 6 clay, and 4 copper ore, and 2 iron ore please?", "I could pay a little, and let you use my anvils"};
																		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages20) {
																			public void finished() {
																				final String[] messages21 = {"Certainly, I will get them for you. Goodbye"};
																				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages21) {
																					public void finished() {
																						owner.addQuest(Config.Quests.DORICS_QUEST, 1);
																						owner.setBusy(false);
																						npc.unblock();
																					}
																				});
																			}
																		});
																		break;
																	case 1:
																		final String[] messages22 = {"That is your choice, nice to meet you anyway"};
																		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages22) {
																			public void finished() {
																				owner.setBusy(false);
																				npc.unblock();
																			}
																		});
																		break;
																}
															}
														});
													}
												});
											}
										});
										break;
									case 1:
										final String[] messages23 = {"How nice to meet someone with such pleasant manners", "Do come again when you need to shout at someone smaller than you"};
										World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages23) {
											public void finished() {
												owner.setBusy(false);
												npc.unblock();
											}
										});
										break;
									case 2:
										final String[] messages24 = {"We have a fine town here, it suits us very well", "Please enjoy your travels. And do visit my friends in their mine"};
										World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages24) {
											public void finished() {
												owner.setBusy(false);
												npc.unblock();
											}
										});
										break;
									case 3:
										final String[] messages25 = {"I make amulets. I am the best maker of them in Runescape"};
										World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages25) {
											public void finished() {
												final String[] messages26 = {"Do you have any to sell?"};
												World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages26) {
													public void finished() {
														final String[] messages27 = {"Not at the moment, sorry. Try again later"};
														World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages27) {
															public void finished() {
																owner.setBusy(false);
																npc.unblock();
															}
														});
													}
												});
											}
										});
										break;
								}
							}
						});
					}
				});
			}
		});
	}

	private void questStarted(final Npc npc, final Player owner) {
		final String[] messages28 = {"Have you got my materials yet traveller?"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages28, true) {
			public void finished() {
				if(owner.getInventory().countId(149) > 5 && owner.getInventory().countId(150) > 3 && owner.getInventory().countId(151) > 1) {
					final String[] messages32 = {"I have everything you need"};
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages32) {
						public void finished() {
							final String[] messages33 = {"Many thanks, pass them here please"};
							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages33) {
								public void finished() {
									World.getDelayedEventHandler().add(new SingleEvent(owner, 1000) {
										public void action() {
											owner.sendMessage("You hand the clay, copper ore, and iron ore to Doric");
											owner.getInventory().remove(new InvItem(149, 6));
											owner.getInventory().remove(new InvItem(149, 6));
											owner.getInventory().remove(new InvItem(149, 6));
											owner.getInventory().remove(new InvItem(149, 6));
											owner.getInventory().remove(new InvItem(149, 6));
											owner.getInventory().remove(new InvItem(149, 6));
											owner.getInventory().remove(new InvItem(150, 4));
											owner.getInventory().remove(new InvItem(150, 4));
											owner.getInventory().remove(new InvItem(150, 4));
											owner.getInventory().remove(new InvItem(150, 4));
											owner.getInventory().remove(new InvItem(151, 1));
											owner.getInventory().remove(new InvItem(151, 1));
											owner.sendInventory();
											final String[] messages34 = {"I can spare you some coins for your trouble"};
											World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages34) {
												public void finished() {
													World.getDelayedEventHandler().add(new SingleEvent(owner, 1000) {
														public void action() {
															owner.sendMessage("Doric hands you 180 coins");
															owner.getInventory().add(new InvItem(10, 180));
															owner.sendInventory();
															final String[] messages35 = {"Please use my anvils any time you want"};
															World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages35) {
																public void finished() {
																	World.getDelayedEventHandler().add(new SingleEvent(owner, 1000) {
																		public void action() {
																			owner.sendMessage("@gre@Well done you have completed Dorics quest");
																			owner.sendMessage("@gre@You have gained 1 quest point!");		
																			owner.incQuestExp(14, 1200);
																			owner.sendStat(14);
																			owner.finishQuest(Config.Quests.DORICS_QUEST);
																			owner.incQuestCompletionStage(Config.Quests.DORICS_QUEST);
																			owner.setBusy(false);
																			npc.unblock();
																			Logger.log(new eventLog(owner.getUsernameHash(), owner.getAccount(), owner.getIP(), DataConversions.getTimeStamp(), "<strong>" + owner.getUsername() + "</strong>" + " has completed <span class=\"recent_quest\">Doric's</span> quest!"));
																		}
																	});
																}
															});
														}
													});
												}
											});
										}
									});
								}
							});
						}
					});
				} else {
					final String[] messages29 = {"Sorry, I don't have them all yet"};
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages29) {
						public void finished() {
							final String[] messages30 = {"Not to worry, stick at it", "Remember I need 6 clay, 4 Copper ore and 2 Iron ore"};
							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages30) {
								public void finished() {
									owner.setBusy(false);
									npc.unblock();
								}
							});
						}
					});				
				}
			}
		});
	}
	
	private void questFinished(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello traveller, how is your Metalworking coming along?"}, true) {
			public void finished() {
				final String[] messages36 = {"Not too bad thanks Doric"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages36) {
					public void finished() {
						final String[] messages37 = {"Good, the love of metal is a thing close to my heart"};
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages37) {
							public void finished() {
								owner.setBusy(false);
								npc.unblock();
							}
						});
					}
				});
			}
		});
	}
}