package com.openrsc.server.database.struct;

public class PlayerData {
	public int playerId;
	public int groupId;
	public int combatStyle;
	public int combatLevel;
	public int totalLevel;
	public long loginDate;
	public long creationDate;
	public String loginIp;
	public int xLocation;
	public int yLocation;
	public int fatigue;
	public int kills;
	public int deaths;
	public int npcKills;
	public int ironMan;
	public int ironManRestriction;
	public int hcIronManDeath;
	public int questPoints;
	public byte blockChat;
	public byte blockPrivate;
	public byte blockTrade;
	public byte blockDuel;
	public boolean cameraAuto;
	public boolean oneMouse;
	public boolean soundOff;
	public int hairColour;
	public int topColour;
	public int trouserColour;
	public int skinColour;
	public int headSprite;
	public int bodySprite;
	public boolean male;
	public String username;
	public String former_name;
	public String pass;
	public String salt;
	public long banned;
	public long muteExpires;
}
