ALTER TABLE `experience` MODIFY `attack` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `defense` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `strength` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `hits` int(9) NOT NULL DEFAULT 4616;
ALTER TABLE `experience` MODIFY `ranged` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `prayer` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `magic` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `cooking` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `woodcut` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `fletching` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `fishing` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `firemaking` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `crafting` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `smithing` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `mining` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `herblaw` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `agility` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY `thieving` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY IF EXISTS `runecraft` int(9) NOT NULL DEFAULT 0;
ALTER TABLE `experience` MODIFY IF EXISTS `harvesting` int(9) NOT NULL DEFAULT 0;