package rsc.enumerations;

public enum FutureJobType {
	OPEN_SOCKET,
	START_THREAD,
	REVERSE_RESOLVE_IP,
	OPEN_DATA_INPUT_STREAM_FROM_URL,
	LIST_DISPLAY_MODES,
	MAKE_FULLSCREEN_FRAME,
	EXIT_FULLSCREEN,
	GET_DECLARED_METHOD,
	GET_DECLARED_FIELD,
	LOAD_MID_PREFS,
	LOAD_MAIN_PREFS,
	MOVE_MOUSE,
	SHOW_CURSOR,
	RUN_COMMAND_LINE,
	SET_CUSTOM_CURSOR,
	GET_CLIPBOARD_CONTENTS,
	SET_CLIPBOARD_CONTENTS,
	FORWARD_RESOLVE_HOSTNAME,
	OPEN_RS_SOCKET
}
