package rsc.enumerations;

public enum PanelControlType {
	LEFT_TEXT,
	CENTERED_TEXT,
	BUTTON_BACKGROUND,
	HORIZ_LINE,
	SCROLLING_LIST_2,
	LEFT_TEXT_ENTRY,
	CENTERED_TEXT_ENTRY,
	HORIZONTAL_LIST,
	CENTERED_LIST,
	SCROLLING_LIST,
	SCROLLING_LIST3,
	BUTTON,
	DECORATED_BOX,
	SPRITE,
	TOGGLE_BUTTON,
	TYPE_15
}
