/**
* Generated By NPCScript :: A scripting engine created for RSCEmulation by Zilent
*/
//npc ID 483
package org.rscemulation.server.npchandler.Biohazard;
import org.rscemulation.server.event.DelayedQuestChat;
import org.rscemulation.server.event.SingleEvent;
import org.rscemulation.server.model.ChatMessage;
import org.rscemulation.server.model.InvItem;
import org.rscemulation.server.model.MenuHandler;
import org.rscemulation.server.model.Npc;
import org.rscemulation.server.model.Player;
import org.rscemulation.server.model.Quest;
import org.rscemulation.server.model.World;
import org.rscemulation.server.npchandler.NpcHandler;



public class Elena implements NpcHandler
 {
	public void handleNpc(final Npc npc, final Player owner) throws Exception
	{
		npc.blockedBy(owner);
		owner.setBusy(true);
		
		Quest q = owner.getQuest(38);
		Quest plagueCity = owner.getQuest(35);
		
		if(q == null)
		{
			if(plagueCity != null && plagueCity.finished())
			{
				noQuestStarted(npc, owner);
			}
			else
			{
				owner.sendMessage("Elena is not interested in talking");
				owner.setBusy(false);
				npc.unblock();
			}
		}
		else if(q != null) 
		{
			if(q.finished()) 
			{
				owner.sendMessage("Elena is not interested in talking");
				owner.setBusy(false);
				npc.unblock();
			}
			else 
			{
				switch(q.getStage())
				{
					case 1:
					case 2:
					case 3:
					case 4:
						questStage1(npc, owner);
					break;
					case 5:
						if(owner.getInventory().countId(804) > 0)
						{
							questStage5(npc, owner);
						}
						else
						{
							noDistill(npc, owner);
						}
					break;
					case 6:
					case 7:
						questStage6(npc, owner);
					break;
					case 8:
						questStage8(npc, owner);
					break;
					case 9:
						questStage9(npc, owner);
					break;
					case 10:
						questStage10(npc, owner);
					break;
				}
			}
		} 
	}
	
	private void noQuestStarted(final Npc npc, final Player owner)
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Good to see you, Elena"}, true)
		{
			public void finished()
			{	
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"You too, thanks for freeing me", "It's just a shame the mourners confiscated my equipment"})
				{
					public void finished()
					{	
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"What did they take?"})
						{
							public void finished()
							{
								World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"My distillator, I can't test any plague samples without it", "They're holding it in the mourner quarters in west ardougne", "I must somehow retrieve that distillator", "If I am to find a cure for this awful affliction"})
								{
									public void finished()
									{
										World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
										{
											public void action()
											{
												final String[] options107 = {"I'll try to retrieve it for you", "Well, good luck"};
												owner.setBusy(false);
												owner.sendMenu(options107);
												owner.setMenuHandler(new MenuHandler(options107) 
												{
													public void handleReply(final int option, final String reply)
													{
														owner.setBusy(true);
														for(Player informee : owner.getViewArea().getPlayersInView())
														{
															informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
														}
														switch(option) 
														{
															case 0:
																acceptQuest(npc, owner);
															break;
															case 1:
																World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Thanks Traveller"})
																{
																	public void finished()
																	{
																		owner.setBusy(false);
																		npc.unblock();
																	}
																});
															break;
														}
													}
												});
											}
										});
									}
								});		
							}
						});
					}
				});
			}	
		});	
	}
	
	private void noDistill(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"So, have you managed to retrieve my distillator?"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"No, I'm afraid not"}) 
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Bring it to me when you get it"}) 
						{
							public void finished()
							{
								owner.setBusy(false);
								npc.unblock();
							}
						});
					}
				});
			}
		});
	}
	
	private void acceptQuest(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"I was hoping you would say that", "Unfortunately they discovered the tunnel and filled it in", "We need another way over the wall"}) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Any ideas?"}) 
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"My father's friend Jerico is in communication with west Ardougne", "He might be able to help", "He lives next to the chapel"}) 
						{
							public void finished()
							{
								owner.addQuest(38, 3);
								owner.incQuestCompletionStage(38);
								owner.setBusy(false);
								npc.unblock();	
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage1(final Npc npc, final Player owner)
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello Elena"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello brave adventurer", "Any lucky finding the distillator?"}) 
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"No, I'm afraid not"}) 
						{
							public void finished()
							{
								World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Speak to Jerico, he will help you to cross the wall", "He lives next to the chapel"}) 
								{
									public void finished()
									{
										owner.setBusy(false);
										npc.unblock();
									}
								});
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage5(final Npc npc, final Player owner)
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"So, have you managed to retrieve my distillator?", "You have, that's great!", "Now can you pass me those refraction agents please?"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
				{
					public void action()
					{
						owner.sendMessage("You hand Elena the distillator and an assortment of vials");
						owner.getInventory().remove(804, 1);
						owner.sendInventory();
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"These look pretty fancy"}) 
						{
							public void finished()
							{
								World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Well, yes and no. The liquid honey isn't worth so much", "But the others are, Especially this colourless ethenea", "And be careful with the sulphuric broline, it's highly poisonous"}) 
								{
									public void finished()
									{
										World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"You're not kidding, I can smell it from here"}) 
										{
											public void finished()
											{
												World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
												{
													public void action()
													{
														owner.sendMessage("Elena puts the agents through the distillator");
														World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"I don't understand... the touch paper hasn't changed colour at all", "You'll need to go and see my old mentor Guidor, he lives in Varrock", "Take these vials and this sample to him"}) 
														{
															public void finished()
															{
																World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
																{
																	public void action()
																	{
																		owner.sendMessage("Elena gives you three vials and a sample in a tin container");
																		owner.getInventory().add(809, 1);
																		owner.getInventory().add(810, 1);
																		owner.getInventory().add(811, 1);
																		owner.getInventory().add(812, 1);
																		owner.sendInventory();
																		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"But first you'll need some more touch-paper", "Go and see the chemist in Rimmington", "Just don't get into any fights, and be careful who you speak to", "Those vials are fragile, and plague carriers don't tend to be too popular"}) 
																		{
																			public void finished()
																			{
																				owner.incQuestCompletionStage(38); //quest stage 6
																				owner.setBusy(false);
																				npc.unblock();
																			}
																		});
																	}
																});
															}
														});
													}
												});
											}
										});
									}
								});
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage6(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello again adventurer", "Have you got the results from Guidor?"}, true) 
		{
			public void finished()
			{
				if (owner.getInventory().countId(809) == 0 || owner.getInventory().countId(810) == 0 || owner.getInventory().countId(811) == 0 || owner.getInventory().countId(812) == 0)
				{
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"I seem to have lost some of the vials you gave me", "Can you give me them again?"}) 
					{
						public void finished()
						{
							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Sure here you go"}) 
							{
								public void finished()
								{
									World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
									{
										public void action()
										{
											owner.sendMessage("Elena gives you three vials and a sample in a tin container");
											owner.getInventory().add(809, 1);
											owner.getInventory().add(810, 1);
											owner.getInventory().add(811, 1);
											owner.getInventory().add(812, 1);
											owner.sendInventory();
											owner.setBusy(false);
											npc.unblock();
										}
									});
								}
							});
						}
					});
				}
				else
				{
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"No not yet"}) 
					{
						public void finished()
						{
							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Remember he lives in Varrock", "Please be careful with those vials"}) 
							{
								public void finished()
								{
									owner.setBusy(false);
									npc.unblock();
								}
							});
						}
					});
				}
			}
		});
	}
	
	private void questStage8(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello again adventurer", "Have you got the results from Guidor?"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"I've given him the sample and test vials", "But I need to speak to him to find out the results"}) 
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Ok do it quickly", "Lives are at stake!"}) 
						{
							public void finished()
							{
								owner.setBusy(false);
								npc.unblock();
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage9(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"You're Back! So what did Guidor say?"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Nothing"}) 
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"What?"}) 
						{
							public void finished()
							{
								World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"He said that there is no plague"}) 
								{
									public void finished()
									{
										World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"So what, this thing has all been a big hoax?"}) 
										{
											public void finished()
											{
												World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Or maybe we're about to uncover something huge"}) 
												{
													public void finished()
													{
														World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Then I think this thing may be bigger than both of us"}) 
														{
															public void finished()
															{
																World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"What do you mean?"}) 
																{
																	public void finished()
																	{
																		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"I mean that you need to go right to the top", "You need to see the King of east Ardougne"}) 
																		{
																			public void finished()
																			{
																				owner.incQuestCompletionStage(38); //quest stage 10
																				owner.setBusy(false);
																				npc.unblock();
																			}
																		});
																	}
																});
															}
														});
													}
												});
											}
										});
									}
								});
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage10(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello Elena"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"You must go to king Lathas immediately"}) 
				{
					public void finished()
					{
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}
	
}