/**
* Generated By NPCScript :: A scripting engine created for RSCEmulation by Zilent
*/
//npc ID 500
package org.rscemulation.server.npchandler.Biohazard;
import org.rscemulation.server.event.DelayedQuestChat;
import org.rscemulation.server.model.Npc;
import org.rscemulation.server.model.Player;
import org.rscemulation.server.model.Quest;
import org.rscemulation.server.model.World;
import org.rscemulation.server.npchandler.NpcHandler;



public class Nurse_Sarah implements NpcHandler
 {
	public void handleNpc(final Npc npc, final Player owner) throws Exception
	{
		npc.blockedBy(owner);
		owner.setBusy(true);
		
		Quest q = owner.getQuest(38);
		Quest plagueCity = owner.getQuest(35);
		
		if(q != null) 
		{	
			if(owner.getQuest(38) != null && owner.getQuest(38).getStage() == 4)
			{
				switch(q.getStage())
				{
					case 4:
						questStage4(npc, owner);
					break;
				}
			}
			else
			{
				owner.sendMessage("Nurse Sarah seems to be too busy to talk");
				owner.setBusy(false);
				npc.unblock();
			}	
		} 
		else
		{
			owner.sendMessage("Nurse Sarah seems to be too busy to talk");
			owner.setBusy(false);
			npc.unblock();
		}
	}
	
	
	
	private void questStage4(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello nurse"}, true)
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Oh hello there", "I'm afraid I can't stop and talk", "A group of mourners have became ill with food poisoning", "I need to go over and see what I can do"})
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hmmm, strange that!"})
						{
							public void finished()
							{
								owner.setBusy(false);
								npc.unblock();
							}
						});
					}
				});			
			}
		});
	}
}