/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent
*/
package org.openrsc.server.npchandler.Merlins_Crystal;
import org.openrsc.server.event.DelayedQuestChat;
import org.openrsc.server.event.SingleEvent;
import org.openrsc.server.model.ChatMessage;
import org.openrsc.server.model.InvItem;
import org.openrsc.server.model.MenuHandler;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.model.World;
import org.openrsc.server.npchandler.NpcHandler;



public class Lady_of_the_lake_two implements NpcHandler {

	public void handleNpc(final Npc npc, final Player owner) throws Exception {
		npc.blockedBy(owner);
		owner.setBusy(true);
		Quest q = owner.getQuest(22);
		if(q != null) {
			if(q.finished()) {
				noQuestStarted(npc, owner);
			} else {
				switch(q.getStage()) {
					case 6:
						questStage6(npc, owner);
						break;
					default:
						noQuestStarted(npc, owner);
				}
			}
		} else {
			noQuestStarted(npc, owner);
		}
	}
	

	private void noQuestStarted(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hello"}, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Go away I'm busy"}) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}
	
	
	private void questStage6(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Hello, Could I have some bread to feed my family?"}, true) {
			public void finished() {
				World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
					public void action() {
						final String[] options107 = {"Sure here you go ", "Sorry I don't have any"};
						owner.setBusy(false);
						owner.sendMenu(options107);
						owner.setMenuHandler(new MenuHandler(options107) {
							public void handleReply(final int option, final String reply) {
								owner.setBusy(true);
								for(Player informee : owner.getViewArea().getPlayersInView()) {
									informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
								}
								switch(option) {
									case 0:
										quest(npc, owner);;
										break;
									case 1:
										goodBye(npc, owner);
										break;
								}
							}
						});
					}
				});
			}
		});
	}
		
		
	private void quest(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Just put it in this bag"}) {
			public void finished() {
				if(owner.getInventory().countId(138) < 1) {
					World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Ops sorry I don't have any"}) {
						public void finished() {
						owner.setBusy(false);
						npc.unblock();
						}
					});
				}
				else
				if(owner.getInventory().countId(138) > 0) {
				owner.sendMessage("You give the homeless man a piece of bread.");
				owner.getInventory().remove(138, 1);
				owner.sendInventory();				
					World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Thank you young one"}) {
						public void finished() {	
							owner.sendMessage("The homeless man winks at you...");
							owner.getInventory().add(new InvItem(606, 1));
							owner.sendInventory();
							owner.incQuestCompletionStage(22);
							owner.sendMessage("...and gives you excalibur!");
							owner.setBusy(false);
							npc.unblock();
						}
					});
				}
			}
		});
	}
	
	
	private void goodBye(final Npc npc, final Player owner) {
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"ok"}) {
			public void finished() {
				owner.setBusy(false);
				npc.unblock();	
			}
		});
	}
	
}