/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent
*/
//npc ID 465
package org.openrsc.server.npchandler.Plague_City;
import org.openrsc.server.Config;
import org.openrsc.server.event.DelayedQuestChat;
import org.openrsc.server.event.SingleEvent;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.model.Quests;
import org.openrsc.server.model.World;
import org.openrsc.server.npchandler.NpcHandler;



public class Elena implements NpcHandler
 {
	public void handleNpc(final Npc npc, final Player owner) throws Exception
	{
		npc.blockedBy(owner);
		owner.setBusy(true);
		Quest q = owner.getQuest(Quests.PLAGUE_CITY);
		if(q != null) 
		{
			if(q.finished()) 
			{
				finished(npc, owner);
			}
			else 
			{
				switch(q.getStage())
				{
					case 12:
						questStage12(npc, owner);
					break;
					case 13:
						questStage13(npc, owner);
					break;
					default:
						noQuestStarted(npc, owner);
				}
			}
		} 
		else 
		{
			noQuestStarted(npc, owner);
		}
	}
	
	
	
	private void questStage12(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Hi, you're free to go", "Your kidnappers don't seem to be about right now"}, true) 
		{
			public void finished()
			{
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Thank you, Being kidnapped was so inconvenient", "I was on my way back to East Ardougne with some samples", "I want to see if I can diagnose a cure for this plague"}) 
				{
					public void finished()
					{
						World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, new String[] {"Well you can leave via the manhole cover near the gate"}) 
						{
							public void finished()
							{
								World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"If you go and see my father", "I'll make sure he adequately rewards you"}) 
								{
									public void finished()
									{
										owner.incQuestCompletionStage(Quests.PLAGUE_CITY);
										owner.setBusy(false);
										npc.unblock();	
									}
								});
							}
						});
					}
				});
			}
		});
	}
	
	private void questStage13(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"If you go and see my father", "I'll make sure he adequately rewards you"}) 
		{
			public void finished()
			{
				owner.setBusy(false);
				npc.unblock();	
			}
		});
	}
	
	private void finished(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
		{
			public void action()
			{
				owner.sendMessage("Elena is not interested in talking");
				owner.setBusy(false);
				npc.unblock();
			}
		});
	}
	
	private void noQuestStarted(final Npc npc, final Player owner) 
	{
		World.getDelayedEventHandler().add(new SingleEvent(owner, 2000)
		{
			public void action()
			{
				owner.sendMessage("Elena is not interested in talking");
				owner.setBusy(false);
				npc.unblock();
			}
		});
	}
	
}