DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    ALTER TABLE `_PREFIX_players` ADD COLUMN `transfer` INT(11);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;