DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
ALTER TABLE `_PREFIX_logins` ADD COLUMN `clientVersion` INT(11);
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;