ALTER TABLE `chat_logs`
    MODIFY COLUMN `_PREFIX_message` VARCHAR (5000) NOT NULL DEFAULT 0;

ALTER TABLE `private_message_logs`
    MODIFY COLUMN `_PREFIX_message` VARCHAR (5000) NOT NULL DEFAULT 0;