/**
* Generated By NPCScript :: A scripting engine created for openrsc by Zilent
*/

package org.openrsc.server.npchandler.Dragon_Slayer;

import org.openrsc.server.Config;
import org.openrsc.server.event.DelayedQuestChat;
import org.openrsc.server.model.ChatMessage;
import org.openrsc.server.model.MenuHandler;
import org.openrsc.server.model.Npc;
import org.openrsc.server.model.Player;
import org.openrsc.server.model.Quest;
import org.openrsc.server.model.Quests;
import org.openrsc.server.model.World;
import org.openrsc.server.npchandler.NpcHandler;
public class Guildmaster implements NpcHandler {
	public void handleNpc(final Npc npc, final Player owner) throws Exception {
		npc.blockedBy(owner);
		owner.setBusy(true);
		Quest q = owner.getQuest(Quests.DRAGON_SLAYER);
		
		
		if(q != null) {
			final String[] messages0 = {"What is this place?"};
			World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages0, true) {
				public void finished() {
					final String[] messages1 = {"This is the champions' guild", "Only adventurers who have proven themselves worthy", "by gaining influence from quests are allowed in here", "As the number of quests in the world rises", "So will the requirements to get in here", "but so will the rewards"};
					World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages1) {
						public void finished() {
							owner.setBusy(false);
							npc.unblock();
						}
					});
				}
			});
		} else {
			final String[] options3 = { "What is this place?", "Do you know where I could get a rune plate mail body?" };
			owner.setBusy(false);
			owner.sendMenu(options3);
			owner.setMenuHandler(new MenuHandler(options3) {
				public void handleReply(final int option, final String reply) {
					owner.setBusy(true);
					for(Player informee : owner.getViewArea().getPlayersInView()) {
						informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
					}
					switch(option) {
						case 0:
							place(npc, owner);
						break;
						
						case 1:
							runeplate(npc, owner);
						break;
					}
				}
			});
		}
	}
	
	private void runeplate(final Npc npc, final Player owner) {
		final String[] messages6 = {"I have a friend called Oziach who lives by the cliffs", "He has a supply of rune plate mail", "He may sell you one if you're lucky", "He can be a little strange sometimes though"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages6) {
			public void finished() {
				owner.addQuest(Quests.DRAGON_SLAYER, 2);
				owner.setBusy(false);
				npc.unblock();
			}
		});
	}
	
	private void place(final Npc npc, final Player owner) {
		final String[] messages7 = {"This is the champions' guild", "Only adventurers who have proved themselves worthy", "by gaining influence from quests are allowed in here", "As the number of quests in the world rises", "So will the requirements to get in here", "But so will the rewards"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages7) {
			public void finished() {
				owner.setBusy(false);
				npc.unblock();
			}
		});
	}
}
