package org.rscemulation.server;

public enum LoginResponse
{
	LOGIN_SUCCESS,
	RECONNECT_SUCCESS,
	INVALID_CREDENTIALS,
	USERNAME_IN_USE,
	CLIENT_NOT_UP_TO_DATE,
	SESSION_REJECTED,
	CHARACTER_BANNED,
	MYSQL_ERROR,
	IP_ALREADY_IN_USE,
	ACCOUNT_ALREADY_IN_USE,
	SERVER_FULL,
	REMOVE_ME_1,
	IP_BANNED,
	CLIENT_DIMENSIONS_TOO_LARGE,
	LOGIN_SERVER_OFFLINE, 
	TOO_MANY_CHARACTERS_IN_WILDERNESS
}
