/**
* Generated By NPCScript :: A scripting engine created for RSCEmulation by Zilent
*/
package org.rscemulation.server.npchandler;

import org.rscemulation.server.event.SingleEvent;
import org.rscemulation.server.model.Npc;
import org.rscemulation.server.model.ChatMessage;
import org.rscemulation.server.model.MenuHandler;
import org.rscemulation.server.model.World;
import org.rscemulation.server.event.DelayedQuestChat;
import org.rscemulation.server.event.MiniEvent;
import org.rscemulation.server.model.Player;
import org.rscemulation.server.model.InvItem;
import org.rscemulation.server.npchandler.NpcHandler;
public class Customs_Officer implements NpcHandler {
	public void handleNpc(final Npc npc, final Player owner) throws Exception {
		npc.blockedBy(owner);
		owner.setBusy(true);
		final String[] options4 = {"Can I board this ship?", "Does Karamja have any unusual customs then?"};
		owner.setBusy(false);
		owner.sendMenu(options4);
		owner.setMenuHandler(new MenuHandler(options4) {
			public void handleReply(final int option, final String reply) {
				owner.setBusy(true);
				for(Player informee : owner.getViewArea().getPlayersInView()) {
					informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
				}
				switch(option) {
					case 0:
						final String[] messages6 = {"You need to be searched before you can board"};
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages6) {
							public void finished() {
								World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
									public void action() {
										final String[] options5 = {"Why?", "Search away I have nothing to hide", "You're not putting your hands on my things"};
										owner.setBusy(false);
										owner.sendMenu(options5);
										owner.setMenuHandler(new MenuHandler(options5) {
											public void handleReply(final int option, final String reply) {
												owner.setBusy(true);
												for(Player informee : owner.getViewArea().getPlayersInView()) {
													informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
												}
												switch(option) {
													case 0:
														final String[] messages7 = {"Because Asgarnia has banned the import of intoxicating spirits"};
														World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages7) {
															public void finished() {
																World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
																	public void action() {
																		final String[] options6 = {"Search Away I have nothing to hide", "You're not putting your hands on my things"};
																		owner.setBusy(false);
																		owner.sendMenu(options6);
																		owner.setMenuHandler(new MenuHandler(options6) {
																			public void handleReply(final int option, final String reply) {
																				owner.setBusy(true);
																				for(Player informee : owner.getViewArea().getPlayersInView()) {
																					informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																				}
																				switch(option) {
																					case 0:
																						if(!owner.getInventory().contains(318)) {
																							final String[] messages8 = {"Well you've got some odd stuff, but it's all legal", "Now you need to pay a boarding charge of 30 gold"};
																							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages8) {
																								public void finished() {
																									World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
																										public void action() {
																											final String[] options7 = {"Ok", "Oh, I'll not bother then"};
																											owner.setBusy(false);
																											owner.sendMenu(options7);
																											owner.setMenuHandler(new MenuHandler(options7) {
																												public void handleReply(final int option, final String reply) {
																													owner.setBusy(true);
																													for(Player informee : owner.getViewArea().getPlayersInView()) {
																														informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																													}
																													switch(option) {
																														case 0:
																															if(owner.getInventory().contains(new InvItem(10, 30))) {
																																World.getDelayedEventHandler().add(new MiniEvent(owner) {
																																	public void action() {
																																		owner.sendMessage("You pay 30 gold");
																																		World.getDelayedEventHandler().add(new MiniEvent(owner) {
																																			public void action() {
																																				owner.sendMessage("You board the ship");
																																				if(npc.getID() == 317) {
																																					World.getDelayedEventHandler().add(new MiniEvent(owner) {
																																						public void action() {
																																							owner.getInventory().remove(10, 30);
																																							owner.sendInventory();
																																							owner.teleport(538, 616, false);
																																							owner.sendMessage("The ship arrives at Ardougne");
																																							owner.setBusy(false);
																																						}
																																					});
																																				} else {
																																					World.getDelayedEventHandler().add(new MiniEvent(owner) {
																																						public void action() {
																																							owner.getInventory().remove(10, 30);
																																							owner.sendInventory();
																																							owner.teleport(268, 650, false);
																																							owner.sendMessage("The ship arrives at Port Sarim");
																																							owner.setBusy(false);
																																						}
																																					});
																																				}
																																			}
																																		});
																																	}
																																});
																															} else {
																																for(Player informee : owner.getViewArea().getPlayersInView()) {
																																	informee.informOfChatMessage(new ChatMessage(owner, "Oh dear I don't seem to have enough money", npc));
																																}
																																owner.setBusy(false);
																															}
																															npc.unblock();
																															break;
																														case 1:
																															owner.setBusy(false);
																															npc.unblock();
																															break;
																													}
																												}
																											});
																										}
																									});
																								}
																							});
																						} else {
																							World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Aha trying to smuggle rum are we?"}) {
																								public void finished() {
																									World.getDelayedEventHandler().add(new SingleEvent(owner, 1000) {
																										public void action() {
																											owner.sendMessage("The customs officer confiscates your rum");
																											while(owner.getInventory().contains(318)) {
																												owner.getInventory().remove(318, 1);
																											}
																											owner.sendInventory();
																											owner.setBusy(false);
																											npc.unblock();
																										}
																									});
																								}
																							});
																						}
																						break;
																					case 1:
																						final String[] messages9 = {"You're not getting on this ship then"};
																						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages9) {
																							public void finished() {
																								owner.setBusy(false);
																								npc.unblock();
																							}
																						});
																						break;
																				}
																			}
																		});
																	}
																});
															}
														});
														break;
													case 1:
														if(!owner.getInventory().contains(318)) {
															final String[] messages8 = {"Well you've got some odd stuff, but it's all legal", "Now you need to pay a boarding charge of 30 gold"};
															World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages8) {
																public void finished() {
																	World.getDelayedEventHandler().add(new SingleEvent(owner, 1500) {
																		public void action() {
																			final String[] options7 = {"Ok", "Oh, I'll not bother then"};
																			owner.setBusy(false);
																			owner.sendMenu(options7);
																			owner.setMenuHandler(new MenuHandler(options7) {
																				public void handleReply(final int option, final String reply) {
																					owner.setBusy(true);
																					for(Player informee : owner.getViewArea().getPlayersInView()) {
																						informee.informOfChatMessage(new ChatMessage(owner, reply, npc));
																					}
																					switch(option) {
																						case 0:
																							if(owner.getInventory().contains(new InvItem(10, 30))) {
																								World.getDelayedEventHandler().add(new MiniEvent(owner) {
																									public void action() {
																										owner.sendMessage("You pay 30 gold");
																										World.getDelayedEventHandler().add(new MiniEvent(owner) {
																											public void action() {
																												owner.sendMessage("You board the ship");
																												if(npc.getID() == 317) {
																													World.getDelayedEventHandler().add(new MiniEvent(owner) {
																														public void action() {
																															owner.getInventory().remove(10, 30);
																															owner.sendInventory();
																															owner.teleport(538, 616, false);
																															owner.sendMessage("The ship arrives at Ardougne");
																															owner.setBusy(false);
																														}
																													});
																												} else {
																													World.getDelayedEventHandler().add(new MiniEvent(owner) {
																														public void action() {
																															owner.getInventory().remove(10, 30);
																															owner.sendInventory();
																															owner.teleport(268, 650, false);
																															owner.sendMessage("The ship arrives at Port Sarim");
																															owner.setBusy(false);
																														}
																													});
																												}
																											}
																										});
																									}
																								});
																							} else {
																								for(Player informee : owner.getViewArea().getPlayersInView()) {
																									informee.informOfChatMessage(new ChatMessage(owner, "Oh dear I don't seem to have enough money", npc));
																								}
																								owner.setBusy(false);
																							}
																							npc.unblock();
																							break;
																						case 1:
																							owner.setBusy(false);
																							npc.unblock();
																							break;
																					}
																				}
																			});
																		}
																	});
																}
															});
														} else {
															World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, new String[] {"Aha trying to smuggle rum are we?"}) {
																public void finished() {
																	World.getDelayedEventHandler().add(new SingleEvent(owner, 1000) {
																		public void action() {
																			owner.sendMessage("The customs officer confiscates your rum");
																			while(owner.getInventory().contains(318)) {
																				owner.getInventory().remove(318, 1);
																			}
																			owner.sendInventory();
																			owner.setBusy(false);
																			npc.unblock();
																		}
																	});
																}
															});
														}
														break;
													case 2:
														final String[] messages10 = {"You're not getting on this ship then"};
														World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages10) {
															public void finished() {
																owner.setBusy(false);
																npc.unblock();
															}
														});
														break;
												}
											}
										});
									}
								});
							}
						});
						break;
					case 1:
						final String[] messages11 = {"I'm not that sort of customs officer"};
						World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages11) {
							public void finished() {
								owner.setBusy(false);
								npc.unblock();
						}
					});
					break;
				}
			}
		});
	}
}