/**
* Generated By NPCScript :: A scripting engine created for RSCEmulation by Zilent
*/
package org.rscemulation.server.npchandler;

import org.rscemulation.server.model.Npc;
import org.rscemulation.server.model.World;
import org.rscemulation.server.event.DelayedQuestChat;
import org.rscemulation.server.model.Player;
import org.rscemulation.server.npchandler.NpcHandler;
public class Pirate implements NpcHandler {
	public void handleNpc(final Npc npc, final Player owner) throws Exception {
		npc.blockedBy(owner);
		owner.setBusy(true);
		switch(new java.util.Random().nextInt(15)) {
			case 0:
				A(npc, owner);
				break;
			case 1:
				B(npc, owner);
				break;
			case 2:
				C(npc, owner);
				break;
			case 3:
				D(npc, owner);
				break;
			case 4:
				E(npc, owner);
				break;
			case 5:
				F(npc, owner);
				break;
			case 6:
				G(npc, owner);
				break;
			case 7:
				H(npc, owner);
				break;
			case 8:
				I(npc, owner);
				break;
			case 9:
				J(npc, owner);
				break;
			case 10:
				K(npc, owner);
				break;
			case 11:
				L(npc, owner);
				break;
			case 12:
				M(npc, owner);
				break;
			case 13:
				N(npc, owner);
				break;
			case 14:
				O(npc, owner);
				break;
		}
	}

	private final void A(final Npc npc, final Player owner) {
		final String[] messages50 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages50, true) {
			public void finished() {
				final String[] messages51 = {"I think ye'll be taking a long walk off a short plank"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages51) {
					public void finished() {
						npc.setAggressive(owner);
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void B(final Npc npc, final Player owner) {
		final String[] messages0 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages0, true) {
			public void finished() {
				final String[] messages1 = {"Arrh, I be in search of buried treasure"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages1) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void C(final Npc npc, final Player owner) {
		final String[] messages2 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages2, true) {
			public void finished() {
				final String[] messages3 = {"Ahoy there"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages3) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void D(final Npc npc, final Player owner) {
		final String[] messages4 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages4, true) {
			public void finished() {
				final String[] messages5 = {"Yo ho ho and bottle of alchopop"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages5) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void E(final Npc npc, final Player owner) {
		final String[] messages16 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages16, true) {
			public void finished() {
				final String[] messages17 = {"I'm the scourge of the seven seas"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages17) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void F(final Npc npc, final Player owner) {
		final String[] messages22 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages22, true) {
			public void finished() {
				final String[] messages23 = {"Keel haul them I say"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages23) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void G(final Npc npc, final Player owner) {
		final String[] messages24 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages24, true) {
			public void finished() {
				final String[] messages25 = {"3 days at port for resupply then out on the high sea"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages25) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void H(final Npc npc, final Player owner) {
		final String[] messages26 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages26, true) {
			public void finished() {
				final String[] messages27 = {"Arrh I'll keel haul ye"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages27) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void I(final Npc npc, final Player owner) {
		final String[] messages28 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages28, true) {
			public void finished() {
				final String[] messages29 = {"Yo ho ho me hearties"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages29) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void J(final Npc npc, final Player owner) {
		final String[] messages30 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages30, true) {
			public void finished() {
				final String[] messages31 = {"Arrh"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages31) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void K(final Npc npc, final Player owner) {
		final String[] messages32 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages32, true) {
			public void finished() {
				final String[] messages33 = {"Shiver me timbers"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages33) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void L(final Npc npc, final Player owner) {
		final String[] messages34 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages34, true) {
			public void finished() {
				final String[] messages35 = {"Arrrh ye lily livered landlubber"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages35) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void M(final Npc npc, final Player owner) {
		final String[] messages40 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages40, true) {
			public void finished() {
				final String[] messages41 = {"Arrh be off with ye"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages41) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void N(final Npc npc, final Player owner) {
		final String[] messages48 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages48, true) {
			public void finished() {
				final String[] messages49 = {"A pox on ye"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages49) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}

	private final void O(final Npc npc, final Player owner) {
		final String[] messages52 = {"Hello"};
		World.getDelayedEventHandler().add(new DelayedQuestChat(owner, npc, messages52, true) {
			public void finished() {
				final String[] messages53 = {"Avast me hearties"};
				World.getDelayedEventHandler().add(new DelayedQuestChat(npc, owner, messages53) {
					public void finished() {
						owner.setBusy(false);
						npc.unblock();
					}
				});
			}
		});
	}
}